# Generated by Django 6.0.6 on 2026-06-29 10:15

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cashflow", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashflowrecord",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Запись ДДС",
                "verbose_name_plural": "Записи ДДС",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="status",
            options={
                "ordering": ["name"],
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
            },
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.AlterModelOptions(
            name="type",
            options={"ordering": ["name"], "verbose_name": "Тип", "verbose_name_plural": "Типы"},
        ),
        migrations.AlterField(
            model_name="cashflowrecord",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Сумма"),
        ),
        migrations.AlterField(
            model_name="cashflowrecord",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="cashflow.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="cashflowrecord",
            name="comment",
            field=models.TextField(blank=True, default="", verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="cashflowrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="cashflowrecord",
            name="date",
            field=models.DateField(default=datetime.date.today, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="cashflowrecord",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="cashflow.status",
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="cashflowrecord",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="cashflow.subcategory",
                verbose_name="Подкатегория",
            ),
        ),
        migrations.AlterField(
            model_name="cashflowrecord",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cashflow.type", verbose_name="Тип"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="cashflow.type",
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="cashflow.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="type",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Название"),
        ),
    ]
